# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(238, 243, 249);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("background-color: rgb(195, 172, 193);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setLineWidth(1)
        self.top_bar.setObjectName("top_bar")
        self.horiz_lay = QtWidgets.QHBoxLayout(self.top_bar)
        self.horiz_lay.setContentsMargins(0, 0, 0, 0)
        self.horiz_lay.setSpacing(0)
        self.horiz_lay.setObjectName("horiz_lay")
        self.frame_toggle = QtWidgets.QFrame(self.top_bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(49, 30, 61);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setLineWidth(1)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_btn = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_btn.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_btn.setSpacing(0)
        self.verticalLayout_btn.setObjectName("verticalLayout_btn")
        self.push_btn_menu = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_btn_menu.sizePolicy().hasHeightForWidth())
        self.push_btn_menu.setSizePolicy(sizePolicy)
        self.push_btn_menu.setStyleSheet("QPushButton{\n"
"    color: rgb(230, 235, 238);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}")
        self.push_btn_menu.setObjectName("push_btn_menu")
        self.verticalLayout_btn.addWidget(self.push_btn_menu)
        self.horiz_lay.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.top_bar)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frame_top)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 6, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toplabelframe = QtWidgets.QFrame(self.frame_3)
        self.toplabelframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toplabelframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toplabelframe.setObjectName("toplabelframe")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.toplabelframe)
        self.horizontalLayout_7.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.toplabelframe)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(44, 22, 35);")
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.horizontalLayout_6.addWidget(self.toplabelframe)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_4.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(49, 30, 61);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_3.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(49, 30, 61);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(49, 30, 61);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.horiz_lay.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left_menu = QtWidgets.QFrame(self.content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(195, 172, 193);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_left_menu_2 = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_left_menu_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu_2.setObjectName("frame_left_menu_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu_btn_1 = QtWidgets.QPushButton(self.frame_left_menu_2)
        self.menu_btn_1.setMinimumSize(QtCore.QSize(0, 40))
        self.menu_btn_1.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(120, 67, 111);\n"
"    border: 0px solid;\n"
"    border-bottom: 1px solid rgb(195, 172, 193);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"\n"
"")
        self.menu_btn_1.setObjectName("menu_btn_1")
        self.verticalLayout_3.addWidget(self.menu_btn_1)
        self.menu_btn_3 = QtWidgets.QPushButton(self.frame_left_menu_2)
        self.menu_btn_3.setMinimumSize(QtCore.QSize(0, 40))
        self.menu_btn_3.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(120, 67, 111);\n"
"    border: 0px solid;\n"
"    border-bottom: 1px solid rgb(195, 172, 193);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"\n"
"")
        self.menu_btn_3.setObjectName("menu_btn_3")
        self.verticalLayout_3.addWidget(self.menu_btn_3)
        self.menu_btn_2 = QtWidgets.QPushButton(self.frame_left_menu_2)
        self.menu_btn_2.setMinimumSize(QtCore.QSize(0, 40))
        self.menu_btn_2.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(120, 67, 111);\n"
"    border: 0px solid;\n"
"    border-bottom: 1px solid rgb(195, 172, 193);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"\n"
"")
        self.menu_btn_2.setObjectName("menu_btn_2")
        self.verticalLayout_3.addWidget(self.menu_btn_2)
        self.verticalLayout_2.addWidget(self.frame_left_menu_2, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frame_left_menu)
        self.frame_chat = QtWidgets.QFrame(self.content)
        self.frame_chat.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_chat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chat.setObjectName("frame_chat")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_chat)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_chat)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"\n"
"  border-top: 1px solid rgb(195, 172, 193);\n"
"  background: rgb(245, 245, 245);\n"
"  background-color: rgb(159, 186, 229); \n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  \n"
" \n"
"  border-left: 1px solid rgb(195, 172, 193);\n"
"  border-bottom: 1px solid rgb(195, 172, 193);\n"
#"  color: rgb(44, 22, 35);\n"
"  background-color: rgb(120, 67, 111);\n"
"\n"
"  padding: 12px;\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"\n"
"  \n"
"  background-color: rgb(203, 151, 174);\n"
"  margin-bottom: -1px; \n"
"}\n"
"\n"
"")
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.brawtab = QtWidgets.QTextBrowser(self.frame)
        self.brawtab.setStyleSheet("border: none")
        self.brawtab.setObjectName("brawtab")
        self.verticalLayout_5.addWidget(self.brawtab)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_4.setStyleSheet("color: rgb(44, 22, 35);\n"
"border-left: 1px solid rgb(195, 172, 193);\n"
"border-top: none")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sendFiletab = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendFiletab.sizePolicy().hasHeightForWidth())
        self.sendFiletab.setSizePolicy(sizePolicy)
        self.sendFiletab.setMinimumSize(QtCore.QSize(40, 20))
        self.sendFiletab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sendFiletab.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(120, 67, 111);\n"
"    border: 0px solid;\n"
"    border-right: 1px solid rgb(195, 172, 193);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"\n"
"")
        self.sendFiletab.setObjectName("sendFiletab")
        self.horizontalLayout_8.addWidget(self.sendFiletab)
        self.emo = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emo.sizePolicy().hasHeightForWidth())
        self.emo.setSizePolicy(sizePolicy)
        self.emo.setMinimumSize(QtCore.QSize(40, 20))
        self.emo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.emo.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(120, 67, 111);\n"
"    border: 0px solid;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"\n"
"")
        self.emo.setObjectName("emo")
        self.horizontalLayout_8.addWidget(self.emo)
        self.verticalLayout_6.addWidget(self.frame_4, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.plaintab = QtWidgets.QPlainTextEdit(self.frame)
        self.plaintab.setMinimumSize(QtCore.QSize(0, 20))
        self.plaintab.setMaximumSize(QtCore.QSize(16777215, 40))
        self.plaintab.setStyleSheet("background-color: rgb(238, 243, 249);")
        self.plaintab.setObjectName("plaintab")
        self.verticalLayout_5.addWidget(self.plaintab)
        self.verticalLayout_4.addWidget(self.frame)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sendButton = QtWidgets.QPushButton(self.frame_2)
        self.sendButton.setMinimumSize(QtCore.QSize(0, 40))
        self.sendButton.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(120, 67, 111);\n"
"    border: 0px solid;\n"
"    border-bottom: 1px solid rgb(195, 172, 193);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"\n"
"")
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_4.addWidget(self.sendButton)
        self.gridLayout.addWidget(self.frame_2, 1, 1, 1, 1)
        self.listWidget = QtWidgets.QTreeWidget(self.page)
        self.listWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.listWidget.setStyleSheet("color: rgb(44, 22, 35);\n"
"border-left: 1px solid rgb(195, 172, 193);\n"
"border-top: none")
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.headerItem().setText(0, "1")
        self.listWidget.header().setVisible(False)
        self.gridLayout.addWidget(self.listWidget, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.exit_btn = QtWidgets.QPushButton(self.page_3)
        self.exit_btn.setGeometry(QtCore.QRect(150, 90, 70, 40))
        self.exit_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.exit_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(120, 67, 111);\n"
"    border: 0px solid;\n"
"    border-bottom: 1px solid rgb(195, 172, 193);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"\n"
"")
        self.exit_btn.setObjectName("exit_btn")
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_chat)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.push_btn_menu.setText(_translate("MainWindow", "Menu"))
        self.label.setText(_translate("MainWindow", "Window Header"))
        self.pushButton_4.setText(_translate("MainWindow", "_"))
        self.pushButton_3.setText(_translate("MainWindow", "O"))
        self.pushButton_2.setText(_translate("MainWindow", "X"))
        self.menu_btn_1.setText(_translate("MainWindow", "Chat"))
        self.menu_btn_3.setText(_translate("MainWindow", "Some BTN"))
        self.menu_btn_2.setText(_translate("MainWindow", "Exit"))
        self.sendFiletab.setText(_translate("MainWindow", "File"))
        self.emo.setText(_translate("MainWindow", "Some BTN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main Chat"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))






class MyBar(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(435, 21)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.barframe = QtWidgets.QFrame(Form)
        self.barframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barframe.setObjectName("frame_6")
        self.barlayout = QtWidgets.QHBoxLayout(self.barframe)
        self.barlayout.setContentsMargins(0, 0, 0, 0)
        self.barlayout.setSpacing(0)
        self.barlayout.setObjectName("horizontalLayout_9")
        self.cancelbtn = QtWidgets.QPushButton(self.barframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelbtn.sizePolicy().hasHeightForWidth())
        self.cancelbtn.setSizePolicy(sizePolicy)
        self.cancelbtn.setMinimumSize(QtCore.QSize(70, 0))
        self.cancelbtn.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 235, 238);\n"
"    background-color: rgb(120, 67, 111);\n"
"    border: 0px solid;\n"
"    border-bottom: 1px solid rgb(195, 172, 193);\n"
"    border-right: 1px solid rgb(195, 172, 193);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 151, 174);\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color: rgb(154, 138, 173);\n"
"}\n"
"")
        self.cancelbtn.setObjectName("pushButton")
        self.barlayout.addWidget(self.cancelbtn)
        self.verticalLayout.addWidget(self.barframe)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cancelbtn.setText(_translate("Form", "Cancel"))
